### ISSUE TITLE
Pure genius

### ISSUE THREAD

**Issue by FGRibreau** [KevinGreene/redis-api#1]
Wow! That's pure genius @KevinGreene !!

redis-api for slack will be **featured** in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet description here](http://redisweekly.com/archive/138.html) :)

**Comment by KevinGreene** [comment]
Thanks, I'm glad you like it! Hopefully it will be useful to a few other people. There's also a small writeup here of the motivation - www.surrealanalysis.com/post/simple-redis-api/
